### ISSUE TITLE
Merge latest Arma Additions into CNTO Additions

### ISSUE THREAD

**Issue by milivojm** [CntoDev/cnto-additions#1]
See PR https://github.com/CntoDev/cnto-additions/pull/41 for details.

**Comment by freghar** [comment]
> Yep. Should be able to do so before the op today.

You are overestimating my free time to create the new repo structure. :)

**Comment by milivojm** [comment]
Will review this hopefully soon.

**Comment by freghar** [comment]
Is there anything else to review?
