### ISSUE TITLE
Feature: Telestation

### ISSUE THREAD

**Issue by Seb105** [CntoDev/cnto-additions#15]
Telestation is a feature that will allow a player at their own discretion to teleport themself back into the action from base after a technical issue, whether it be getting Arma'd or DC'd. This would not require Zeus permission, but would inform the zeus it happened.

General principles:
- Entirely player-driven, no zeus intervention needed
- Player can choose who the teleport target is
- Do not teleport player near enemies or within LoS of friendlies
- Log use of feature (diag_log or inform zeus)

**Comment by JamesTheClarke** [comment]
Closing issue since relevant PR was merged into Master
