### ISSUE TITLE
"Order" group attribute

### ISSUE THREAD

**Issue by Seb105** [CntoDev/cnto-additions#33]
A common issue with our compositions are that due to the fact that units in mission slotting are ordered in the order that groups are created in the editor, any shuffling of units is liable to break ordering without anyone noticing.

By implementing an "order" 3den attribute, such as PLT being 1, Alpha Being 2 etc a validation check could be introduced to ensure that units in the mission are in the order the composition desires by checking that the sequential order of the https://community.bistudio.com/wiki/get3DENEntityID groups are equal the the sequential order of the order attributes.

**Comment by freghar** [comment]
Unfortunately, as I found out with https://github.com/freghar/arma-additions/blob/master/addons/editor_extensions/validate_mission/checks/fn_checkOrdering.sqf , this isn't always a guarantee. This check works only sometimes.

It seems to be reliable when deleting/placing units, but cut/paste seems to refresh the entity ID (assign biggest), but without changing some internal ordering value, meaning the playable slots would still be out of order, even if the entity IDs are in order.

**Comment by Seb105** [comment]
Closing due to engine limitation
